version: "3"
services: 
  db:
    image: mariadb
    env_file: .env
    volumes: 
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
      - exchangedb:/var/lib/mysql
    ports: 
      - "3308:3306"
      
  app:
    image: golang:1.12
    env_file: .env
    volumes: 
      - ./:/app
    working_dir: /app
    command: ["./wait-for-it.sh", "db:3306", "--timeout=30", "--", "make", "run"]
    ports: 
      - "8080:8080"
    depends_on: 
      - db

#volumes
volumes: 
    exchangedb: